Add kubernetes-proxy and kubelet setup

diff --git a/scripts/generate-ssl-certificates b/scripts/generate-ssl-certificates
--- a/scripts/generate-ssl-certificates
+++ b/scripts/generate-ssl-certificates
@@ -7,7 +7,7 @@ readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 pushd "${dir}/../certificates" >/dev/null
 trap 'popd >/dev/null' EXIT
 
-rm -vf ./*.csr ./*.pem
+find . \( -iname '*.csr' -o -iname '*.pem' \) -print0 | xargs -0 -r rm -v
 
 # ca
 cfssl gencert -initca ca-csr.json | cfssljson -bare ca
@@ -37,3 +37,43 @@ cfssl gencert \
   -config=ca-config.json \
   -profile=kubernetes \
   admin-csr.json | cfssljson -bare admin
+
+# proxy
+cfssl gencert \
+  -ca=ca.pem \
+  -ca-key=ca-key.pem \
+  -config=ca-config.json \
+  -profile=kubernetes \
+  kube-proxy-csr.json | cfssljson -bare kube-proxy
+
+# node
+for i in {0..5}; do
+  read -r -d '' CSR << EOF || true # absorb non-zero return from read
+{
+  "CN": "system:node:node-${i}",
+  "key": {
+    "algo": "rsa",
+    "size": 2048
+  },
+  "names": [
+    {
+      "C": "DE",
+      "L": "Berlin",
+      "O": "system:nodes",
+      "OU": "Kubernetes The Hab Way",
+      "ST": "Berlin"
+    }
+  ]
+}
+EOF
+
+  mkdir -p "node-${i}"
+
+  echo "${CSR}" | cfssl gencert \
+    -ca=ca.pem \
+    -ca-key=ca-key.pem \
+    -config=ca-config.json \
+    -hostname="node-${i},192.168.222.1${i}" \
+    -profile=kubernetes \
+    - | cfssljson -bare "node-${i}/node"
+done
